// Runtime-agnostic ndn_types test cases.
//
// These cases are written against a small `Tap` assertion interface so they
// can be driven from any runtime: jest (node) wraps each case as `it(...)`
// and re-throws assertion failures as jest errors; the browser runner in
// tests/browser/real-browser/ndn_types_runner.ts provides its own Tap impl
// that records pass/fail to the DOM. Adding a new case here automatically
// covers both runtimes.

import {
    bytesToHex,
    hexToBytes,
    base32Encode,
    base32Decode,
    varintEncode,
    varintDecode,
    canonicalizeJson,
    toCanonicalJsonString,
    sha256Utf8,
    HashMethod,
    ChunkType,
    ObjId,
    ChunkId,
    buildObjId,
    buildNamedObjectByJson,
    verifyNamedObject,
    verifyNamedObjectFromStr,
    loadNamedObjectFromObjStr,
    extractObjIdByPath,
    BaseContentObject,
    FileObject,
    PathObject,
    InclusionProof,
    SimpleMapItem,
    SimpleObjectMap,
    DirObject,
    SimpleChunkList,
    RelationObject,
    KnownStandardObject,
    NdnError,
    OBJ_TYPE_FILE,
    OBJ_TYPE_DIR,
    OBJ_TYPE_PATH,
    OBJ_TYPE_RELATION,
    OBJ_TYPE_INCLUSION_PROOF,
    OBJ_TYPE_CHUNK_LIST_SIMPLE,
    RELATION_TYPE_SAME,
    RELATION_TYPE_PART_OF,
} from '../src/ndn_types'

// Cross-runtime fixture generated by the Rust ndn-lib reference impl. Each
// entry pairs a `${type}:${hex}` ObjId with the JSON value the Rust code
// hashed to produce it. Verifying these end-to-end is the strongest possible
// protocol-correctness check for our TypeScript port: if the SHA-256 of our
// canonical JSON serialization matches the Rust ObjId for every entry, the
// canonicalization, key sort, hash, and ObjId encoding are all on-the-wire
// compatible with the Rust crate.
import ndnObjectFixture from './ndn_object.json'

// ============================================================
// Tap — minimal cross-runtime assertion interface
// ============================================================

export interface Tap {
    /** Strict (===) equality. */
    eq<T>(actual: T, expected: T, msg?: string): void
    /** Structural (recursive value) equality. */
    deepEq(actual: unknown, expected: unknown, msg?: string): void
    /** Asserts !!value. */
    truthy(value: unknown, msg?: string): void
    /** Asserts !value. */
    falsy(value: unknown, msg?: string): void
    /** Asserts value === null. */
    isNull(value: unknown, msg?: string): void
    /**
     * Asserts that fn() throws. If `kind` is provided, it must equal the
     * thrown NdnError's `kind` property.
     */
    throws(fn: () => unknown, kind?: string, msg?: string): void
}

export interface NdnTypesTestCase {
    name: string
    run(t: Tap): void
}

// Default tap implementation: throws plain Errors with descriptive messages.
// Both jest and the browser runner can use this directly; jest's failure
// messages are slightly less rich than native expect() (no diff output) but
// the test names + messages still pinpoint the failure.
function fmt(value: unknown): string {
    if (value instanceof Uint8Array) {
        return `Uint8Array[${Array.from(value).join(',')}]`
    }
    try {
        return JSON.stringify(value)
    } catch {
        return String(value)
    }
}

function deepEqual(a: unknown, b: unknown): boolean {
    if (a === b) return true
    if (a === null || b === null) return false
    if (typeof a !== typeof b) return false
    if (typeof a !== 'object') return false
    if (a instanceof Uint8Array || b instanceof Uint8Array) {
        if (!(a instanceof Uint8Array) || !(b instanceof Uint8Array)) return false
        if (a.length !== b.length) return false
        for (let i = 0; i < a.length; i++) {
            if (a[i] !== b[i]) return false
        }
        return true
    }
    if (Array.isArray(a) || Array.isArray(b)) {
        if (!Array.isArray(a) || !Array.isArray(b)) return false
        if (a.length !== b.length) return false
        for (let i = 0; i < a.length; i++) {
            if (!deepEqual(a[i], b[i])) return false
        }
        return true
    }
    const ao = a as Record<string, unknown>
    const bo = b as Record<string, unknown>
    const ak = Object.keys(ao)
    const bk = Object.keys(bo)
    if (ak.length !== bk.length) return false
    for (const k of ak) {
        if (!Object.prototype.hasOwnProperty.call(bo, k)) return false
        if (!deepEqual(ao[k], bo[k])) return false
    }
    return true
}

export const defaultTap: Tap = {
    eq(actual, expected, msg) {
        if (actual !== expected) {
            throw new Error(
                `${msg ?? 'eq'}: expected ${fmt(expected)}, got ${fmt(actual)}`,
            )
        }
    },
    deepEq(actual, expected, msg) {
        if (!deepEqual(actual, expected)) {
            throw new Error(
                `${msg ?? 'deepEq'}: expected ${fmt(expected)}, got ${fmt(actual)}`,
            )
        }
    },
    truthy(value, msg) {
        if (!value) {
            throw new Error(`${msg ?? 'truthy'}: expected truthy, got ${fmt(value)}`)
        }
    },
    falsy(value, msg) {
        if (value) {
            throw new Error(`${msg ?? 'falsy'}: expected falsy, got ${fmt(value)}`)
        }
    },
    isNull(value, msg) {
        if (value !== null) {
            throw new Error(`${msg ?? 'isNull'}: expected null, got ${fmt(value)}`)
        }
    },
    throws(fn, kind, msg) {
        let thrown: unknown = null
        try {
            fn()
        } catch (e) {
            thrown = e
        }
        if (thrown == null) {
            throw new Error(`${msg ?? 'throws'}: expected fn to throw`)
        }
        if (kind != null) {
            if (!(thrown instanceof NdnError)) {
                throw new Error(
                    `${msg ?? 'throws'}: expected NdnError(${kind}), got ${
                        (thrown as Error)?.message ?? String(thrown)
                    }`,
                )
            }
            if (thrown.kind !== kind) {
                throw new Error(
                    `${msg ?? 'throws'}: expected NdnError kind=${kind}, got kind=${thrown.kind}`,
                )
            }
        }
    },
}

// ============================================================
// Test cases
// ============================================================

export const NDN_TYPES_TEST_CASES: NdnTypesTestCase[] = [
    // ----- low-level encoding helpers -----
    {
        name: 'hex round-trips',
        run(t) {
            const bytes = new Uint8Array([0x00, 0x01, 0x7f, 0x80, 0xab, 0xff])
            const hex = bytesToHex(bytes)
            t.eq(hex, '00017f80abff')
            t.deepEq(Array.from(hexToBytes(hex)), Array.from(bytes))
        },
    },
    {
        name: 'hexToBytes rejects invalid input',
        run(t) {
            t.throws(() => hexToBytes('abc'), 'InvalidId')
            t.throws(() => hexToBytes('zz'), 'InvalidId')
        },
    },
    {
        name: 'base32 round-trips (RFC4648 lowercase, no padding)',
        run(t) {
            const bytes = new Uint8Array([0x66, 0x6f, 0x6f, 0x62, 0x61, 0x72])
            const enc = base32Encode(bytes)
            t.eq(enc, 'mzxw6ytboi')
            t.deepEq(Array.from(base32Decode(enc)), Array.from(bytes))
        },
    },
    {
        name: 'base32Decode rejects invalid characters',
        run(t) {
            t.throws(() => base32Decode('!'), 'InvalidId')
        },
    },
    {
        name: 'varint round-trips for representative values',
        run(t) {
            for (const n of [0, 1, 127, 128, 255, 16383, 16384, 1234567, 0x7fffffff]) {
                const enc = varintEncode(n)
                const [dec, consumed] = varintDecode(enc, 0)
                t.eq(dec, n, `varint(${n})`)
                t.eq(consumed, enc.length, `consumed(${n})`)
            }
        },
    },
    {
        name: 'varintEncode rejects bad input',
        run(t) {
            t.throws(() => varintEncode(-1), 'InvalidParam')
            t.throws(() => varintEncode(1.5), 'InvalidParam')
            t.throws(() => varintEncode(Number.POSITIVE_INFINITY), 'InvalidParam')
        },
    },
    {
        name: 'varintDecode rejects truncated input',
        run(t) {
            t.throws(() => varintDecode(new Uint8Array([0x80])), 'InvalidData')
        },
    },

    // ----- canonical JSON -----
    {
        name: 'canonicalizeJson sorts object keys recursively but preserves arrays',
        run(t) {
            const input = {
                b: 1,
                a: { y: [3, { z: 1, a: 2 }], x: 'hi' },
            }
            const canon = canonicalizeJson(input)
            t.deepEq(Object.keys(canon), ['a', 'b'])
            t.deepEq(Object.keys(canon.a), ['x', 'y'])
            t.deepEq(Object.keys(canon.a.y[1]), ['a', 'z'])
            t.eq(canon.a.y[0], 3)
        },
    },
    {
        name: 'toCanonicalJsonString is deterministic across key orders',
        run(t) {
            const a = { b: 2, a: { y: 1, x: 0 } }
            const b = { a: { x: 0, y: 1 }, b: 2 }
            t.eq(toCanonicalJsonString(a), toCanonicalJsonString(b))
            t.eq(toCanonicalJsonString(a), '{"a":{"x":0,"y":1},"b":2}')
        },
    },

    // ----- HashMethod / ChunkType -----
    {
        name: 'HashMethod.hashResultSize matches expected sizes',
        run(t) {
            t.eq(HashMethod.hashResultSize('sha256'), 32)
            t.eq(HashMethod.hashResultSize('sha512'), 64)
            t.eq(HashMethod.hashResultSize('blake2s256'), 32)
        },
    },
    {
        name: 'HashMethod.parse strips mix prefix',
        run(t) {
            t.deepEq(HashMethod.parse('mix256'), ['sha256', true])
            t.deepEq(HashMethod.parse('sha256'), ['sha256', false])
            t.deepEq(HashMethod.parse('mix512'), ['sha512', true])
        },
    },
    {
        name: 'HashMethod.fromString throws on unknown',
        run(t) {
            t.throws(() => HashMethod.fromString('md5'), 'InvalidData')
        },
    },
    {
        name: 'ChunkType isMix / isChunkType',
        run(t) {
            t.eq(ChunkType.isMix('mix256'), true)
            t.eq(ChunkType.isMix('sha256'), false)
            t.eq(ChunkType.isMix('qcid'), true)
            t.eq(ChunkType.isChunkType('sha256'), true)
            t.eq(ChunkType.isChunkType('not-a-real-type'), false)
        },
    },
    {
        name: 'ChunkType.fromHashType respects mix flag',
        run(t) {
            t.eq(ChunkType.fromHashType('sha256', true), 'mix256')
            t.eq(ChunkType.fromHashType('sha256', false), 'sha256')
            t.eq(ChunkType.fromHashType('blake2s256', true), 'mixblake2s256')
            t.throws(() => ChunkType.fromHashType('qcid', false), 'InvalidObjType')
        },
    },
    {
        name: 'ChunkType.toHashMethod',
        run(t) {
            t.eq(ChunkType.toHashMethod('mix256'), 'sha256')
            t.eq(ChunkType.toHashMethod('sha512'), 'sha512')
            t.throws(() => ChunkType.toHashMethod('bogus'), 'InvalidObjType')
        },
    },

    // ----- ObjId -----
    {
        name: 'ObjId toString / fromString round-trip via type:hex form',
        run(t) {
            const sample = new Uint8Array(32).fill(0xab)
            const id = new ObjId('cyfile', sample)
            const s = id.toString()
            t.eq(s.startsWith('cyfile:'), true)
            const back = ObjId.fromString(s)
            t.eq(back.equals(id), true)
        },
    },
    {
        name: 'ObjId toBase32 / fromString round-trip via base32 form',
        run(t) {
            const sample = new Uint8Array(32).fill(0xab)
            const id = new ObjId('cyfile', sample)
            const b32 = id.toBase32()
            t.eq(b32.includes(':'), false)
            const back = ObjId.fromString(b32)
            t.eq(back.equals(id), true)
        },
    },
    {
        name: 'ObjId toBytes / fromBytes round-trip',
        run(t) {
            const id = new ObjId('cydir', new Uint8Array(32).fill(0xab))
            const back = ObjId.fromBytes(id.toBytes())
            t.eq(back.equals(id), true)
        },
    },
    {
        name: 'ObjId toJSON serializes as the type:hex string',
        run(t) {
            const id = new ObjId('cyfile', new Uint8Array([0x01, 0x02, 0x03]))
            t.eq(JSON.stringify({ id }), '{"id":"cyfile:010203"}')
        },
    },
    {
        name: 'ObjId fromHostname uses the leading label',
        run(t) {
            const id = new ObjId('cyfile', new Uint8Array(32).fill(0xab))
            const host = `${id.toBase32()}.example.com`
            const back = ObjId.fromHostname(host)
            t.eq(back.equals(id), true)
        },
    },
    {
        name: 'ObjId fromPath finds an embedded ObjId and returns the suffix',
        run(t) {
            const id = new ObjId('cyfile', new Uint8Array(32).fill(0xab))
            const path = `/foo/${id.toBase32()}/bar/baz`
            const { objId, subPath } = ObjId.fromPath(path)
            t.eq(objId.equals(id), true)
            t.eq(subPath, '/bar/baz')
        },
    },
    {
        name: 'ObjId fromPath returns null subPath when ObjId is the trailing element',
        run(t) {
            const id = new ObjId('cyfile', new Uint8Array(32).fill(0xab))
            const { objId, subPath } = ObjId.fromPath(`/foo/${id.toBase32()}`)
            t.eq(objId.equals(id), true)
            t.isNull(subPath)
        },
    },
    {
        name: 'ObjId fromPath throws when no segment is a valid ObjId',
        run(t) {
            t.throws(() => ObjId.fromPath('/foo/bar/baz'), 'InvalidId')
        },
    },
    {
        name: 'ObjId classification helpers',
        run(t) {
            const sample = new Uint8Array(32).fill(0xab)
            t.eq(new ObjId(OBJ_TYPE_FILE, sample).isFileObject(), true)
            t.eq(new ObjId(OBJ_TYPE_DIR, sample).isDirObject(), true)
            t.eq(new ObjId(OBJ_TYPE_DIR, sample).isContainer(), true)
            t.eq(new ObjId('sha256', sample).isChunk(), true)
            t.eq(new ObjId(OBJ_TYPE_FILE, sample).isJson(), true)
            t.eq(new ObjId(OBJ_TYPE_DIR, sample).isJson(), false)
            t.eq(new ObjId('sha256', sample).isJson(), false)
        },
    },
    {
        name: 'ObjId fromString rejects malformed input',
        run(t) {
            t.throws(() => ObjId.fromString('a:b:c'), 'InvalidId')
        },
    },

    // ----- ChunkId -----
    {
        name: 'ChunkId.fromMix256Result encodes data length as varint prefix and getLength reads it back',
        run(t) {
            const fakeHash = new Uint8Array(32).fill(0x42)
            const c = ChunkId.fromMix256Result(123456, fakeHash)
            t.eq(c.chunkType, 'mix256')
            const lenPrefix = varintEncode(123456)
            t.eq(c.hashResult.length, lenPrefix.length + 32)
            t.deepEq(
                Array.from(c.hashResult.slice(0, lenPrefix.length)),
                Array.from(lenPrefix),
            )
            t.eq(c.getLength(), 123456)
        },
    },
    {
        name: 'non-mix ChunkId returns null length',
        run(t) {
            const c = ChunkId.fromSha256Result(new Uint8Array(32))
            t.isNull(c.getLength())
        },
    },
    {
        name: 'ChunkId toString / fromString round-trip',
        run(t) {
            const c = ChunkId.fromMix256Result(42, new Uint8Array(32).fill(0x11))
            const back = ChunkId.fromString(c.toString())
            t.eq(back.chunkType, c.chunkType)
            t.deepEq(Array.from(back.hashResult), Array.from(c.hashResult))
        },
    },
    {
        name: 'ChunkId.toDidString prefix',
        run(t) {
            const c = ChunkId.fromSha256Result(new Uint8Array([0x01, 0x02]))
            t.eq(c.toDidString(), 'did:sha256:0102')
        },
    },
    {
        name: 'ChunkId.fromString rejects non-chunk types',
        run(t) {
            const id = new ObjId('cyfile', new Uint8Array(32))
            t.throws(() => ChunkId.fromString(id.toString()), 'InvalidId')
        },
    },
    {
        name: 'ChunkId.equalsHash compares raw bytes',
        run(t) {
            const hash = new Uint8Array(32).fill(7)
            const c = ChunkId.fromSha256Result(hash)
            t.eq(c.equalsHash(hash), true)
            t.eq(c.equalsHash(new Uint8Array(32)), false)
        },
    },

    // ----- buildNamedObjectByJson / verify -----
    {
        name: 'buildObjId hash matches direct sha256 of canonical JSON',
        run(t) {
            const value = { b: 2, a: 1 }
            const canon = toCanonicalJsonString(value)
            const expected = sha256Utf8(canon)
            const id = buildObjId('cyfile', canon)
            t.deepEq(Array.from(id.objHash), Array.from(expected))
            t.eq(id.objType, 'cyfile')
        },
    },
    {
        name: 'buildNamedObjectByJson is invariant under input key order',
        run(t) {
            const [id1, str1] = buildNamedObjectByJson('cyfile', { b: 2, a: 1 })
            const [id2, str2] = buildNamedObjectByJson('cyfile', { a: 1, b: 2 })
            t.eq(id1.equals(id2), true)
            t.eq(str1, str2)
            t.eq(str1, '{"a":1,"b":2}')
        },
    },
    {
        name: 'verifyNamedObject succeeds for matching data',
        run(t) {
            const [id] = buildNamedObjectByJson('cyfile', { foo: 'bar' })
            t.eq(verifyNamedObject(id, { foo: 'bar' }), true)
        },
    },
    {
        name: 'verifyNamedObject fails on mutation',
        run(t) {
            const [id] = buildNamedObjectByJson('cyfile', { foo: 'bar' })
            t.eq(verifyNamedObject(id, { foo: 'baz' }), false)
        },
    },
    {
        name: 'verifyNamedObjectFromStr returns parsed value or throws',
        run(t) {
            const value = { foo: 'bar', n: 1 }
            const [id, str] = buildNamedObjectByJson('cyfile', value)
            t.deepEq(verifyNamedObjectFromStr(id, str), value)
            t.throws(() => verifyNamedObjectFromStr(id, '{"foo":"bar","n":2}'), 'InvalidId')
            t.throws(() => verifyNamedObjectFromStr(id, 'not json'), 'InvalidId')
        },
    },
    {
        name: 'loadNamedObjectFromObjStr only accepts JSON-shaped strings',
        run(t) {
            t.deepEq(loadNamedObjectFromObjStr('{"a":1}'), { a: 1 })
            t.throws(() => loadNamedObjectFromObjStr('plain'), 'Unsupported')
        },
    },

    // ----- extractObjIdByPath -----
    {
        name: 'extractObjIdByPath walks objects and arrays',
        run(t) {
            const id = new ObjId('cyfile', new Uint8Array(32).fill(1))
            const tree = { a: { b: [{ c: id.toString() }] } }
            const found = extractObjIdByPath(tree, '/a/b/0/c')
            t.eq(found.equals(id), true)
        },
    },
    {
        name: 'extractObjIdByPath throws on missing path',
        run(t) {
            t.throws(() => extractObjIdByPath({ a: 1 }, '/a/b'), 'InvalidParam')
            t.throws(() => extractObjIdByPath({}, '/missing'), 'InvalidParam')
        },
    },
    {
        name: 'extractObjIdByPath throws when target is not a valid ObjId string',
        run(t) {
            t.throws(() => extractObjIdByPath({ x: 'not-an-id' }, '/x'), 'InvalidData')
        },
    },

    // ----- BaseContentObject -----
    {
        name: 'BaseContentObject skips empty/default fields on serialization',
        run(t) {
            const base = new BaseContentObject({
                name: 'hello',
                create_time: 100,
                last_update_time: 200,
            })
            const json = base.toJSON()
            t.deepEq(json, { name: 'hello', create_time: 100, last_update_time: 200 })
            t.eq('did' in json, false)
            t.eq('tags' in json, false)
        },
    },
    {
        name: 'BaseContentObject emits non-empty optional fields and serializes base_on as string',
        run(t) {
            const baseOnId = new ObjId('cyfile', new Uint8Array(32).fill(2))
            const base = new BaseContentObject({
                did: 'did:test:1',
                name: 'n',
                tags: ['x'],
                base_on: baseOnId,
                exp: 999,
            })
            const json = base.toJSON() as Record<string, unknown>
            t.eq(json.did, 'did:test:1')
            t.deepEq(json.tags, ['x'])
            t.eq(json.base_on, baseOnId.toString())
            t.eq(json.exp, 999)
        },
    },

    // ----- FileObject -----
    {
        name: 'FileObject genObjId is deterministic and verifiable',
        run(t) {
            const f = new FileObject('readme.md', 1024, 'sha256:' + '00'.repeat(32))
            f.content_obj.create_time = 1700000000
            f.content_obj.last_update_time = 1700000001
            const [id1, str1] = f.genObjId()
            const [id2, str2] = f.genObjId()
            t.eq(id1.equals(id2), true)
            t.eq(str1, str2)
            t.eq(id1.objType, OBJ_TYPE_FILE)
            t.eq(verifyNamedObject(id1, JSON.parse(str1)), true)
        },
    },
    {
        name: 'FileObject round-trips via fromJSON / toJSON',
        run(t) {
            const f = new FileObject('a.bin', 42, 'sha256:' + 'ab'.repeat(32))
            f.content_obj.create_time = 100
            f.content_obj.last_update_time = 200
            f.meta = { foo: 'bar', n: 7 }
            const json = f.toJSON()
            const f2 = FileObject.fromJSON(json as Record<string, unknown>)
            t.eq(f2.size, 42)
            t.eq(f2.content, 'sha256:' + 'ab'.repeat(32))
            t.eq(f2.content_obj.name, 'a.bin')
            t.eq(f2.content_obj.create_time, 100)
            t.deepEq(f2.meta, { foo: 'bar', n: 7 })
            t.eq(f.genObjId()[0].equals(f2.genObjId()[0]), true)
        },
    },
    {
        name: 'FileObject puts meta fields at the JSON root, not in a nested object',
        run(t) {
            const f = new FileObject('x', 1, '')
            f.meta = { custom: 'value' }
            const json = f.toJSON() as Record<string, unknown>
            t.eq(json.custom, 'value')
            t.eq('meta' in json, false)
        },
    },

    // ----- PathObject -----
    {
        name: 'PathObject toJSON / fromJSON round-trip',
        run(t) {
            const target = new ObjId('cyfile', new Uint8Array(32).fill(3))
            const p = new PathObject('/data/foo', target, 1000, 2000)
            const json = p.toJSON()
            t.deepEq(json, {
                path: '/data/foo',
                uptime: 1000,
                target: target.toString(),
                exp: 2000,
            })
            const back = PathObject.fromJSON(json)
            t.eq(back.path, '/data/foo')
            t.eq(back.uptime, 1000)
            t.eq(back.exp, 2000)
            t.eq(back.target.equals(target), true)
        },
    },
    {
        name: 'PathObject genObjId uses cypath type',
        run(t) {
            const target = new ObjId('cyfile', new Uint8Array(32).fill(3))
            const p = new PathObject('/x', target, 1, 2)
            const [id] = p.genObjId()
            t.eq(id.objType, OBJ_TYPE_PATH)
        },
    },

    // ----- InclusionProof -----
    {
        name: 'InclusionProof genObjId produces a verifiable cyinc id',
        run(t) {
            const target = new ObjId('cyfile', new Uint8Array(32).fill(4))
            const proof = new InclusionProof(
                target,
                { hello: 'world' },
                'did:test:curator',
                5,
                ['cat-a'],
            )
            proof.iat = 1
            proof.exp = 2
            const [id, str] = proof.genObjId()
            t.eq(id.objType, OBJ_TYPE_INCLUSION_PROOF)
            t.eq(verifyNamedObject(id, JSON.parse(str)), true)
        },
    },

    // ----- SimpleObjectMap / SimpleMapItem -----
    {
        name: 'SimpleMapItem fromObjId encodes as a string in toJSON',
        run(t) {
            const id = new ObjId('cyfile', new Uint8Array(32).fill(5))
            const item = SimpleMapItem.fromObjId(id)
            t.eq(SimpleMapItem.toJSON(item), id.toString())
        },
    },
    {
        name: 'SimpleMapItem fromObject encodes as { obj_type, body }',
        run(t) {
            const item = SimpleMapItem.fromObject('cyfile', { hello: 1 })
            t.deepEq(SimpleMapItem.toJSON(item), {
                obj_type: 'cyfile',
                body: { hello: 1 },
            })
        },
    },
    {
        name: 'SimpleMapItem.fromJSON round-trip for both shapes',
        run(t) {
            const id = new ObjId('cyfile', new Uint8Array(32).fill(6))
            const a = SimpleMapItem.fromJSON(id.toString())
            t.eq(a.kind, 'objId')
            const b = SimpleMapItem.fromJSON({ obj_type: 'cyfile', body: { x: 1 } })
            t.eq(b.kind, 'object')
            const c = SimpleMapItem.fromJSON({ obj_type: 'cyfile', jwt: 'tok' })
            t.eq(c.kind, 'objectJwt')
            t.throws(() => SimpleMapItem.fromJSON({}), 'InvalidData')
            t.throws(() => SimpleMapItem.fromJSON({ obj_type: 'cyfile' }), 'InvalidData')
        },
    },
    {
        name: 'SimpleObjectMap toJSON / fromJSON round-trip',
        run(t) {
            const id = new ObjId('cyfile', new Uint8Array(32).fill(7))
            const map = new SimpleObjectMap()
            map.set('a', SimpleMapItem.fromObjId(id))
            map.set('b', SimpleMapItem.fromObject('cyfile', { name: 'b' }))
            const json = map.toJSON()
            const back = SimpleObjectMap.fromJSON(json)
            t.eq(back.size, 2)
            t.eq(back.has('a'), true)
            t.eq(back.has('b'), true)
            const a = back.get('a')!
            t.eq(a.kind, 'objId')
            if (a.kind === 'objId') t.eq(a.objId.equals(id), true)
        },
    },
    {
        name: 'SimpleObjectMap.genObjIdWithRealObj resolves children to ObjId strings',
        run(t) {
            const childId = new ObjId('cyfile', new Uint8Array(32).fill(8))
            const map = new SimpleObjectMap()
            map.set('child', SimpleMapItem.fromObjId(childId))
            const realObj: Record<string, unknown> = { name: 'parent' }
            const [id, str] = map.genObjIdWithRealObj(OBJ_TYPE_DIR, realObj)
            t.eq(id.objType, OBJ_TYPE_DIR)
            const parsed = JSON.parse(str) as Record<string, unknown>
            t.eq((parsed.body as Record<string, string>).child, childId.toString())
            t.eq(parsed.name, 'parent')
        },
    },

    // ----- DirObject -----
    {
        name: 'DirObject.addFile updates counters and entries',
        run(t) {
            const dir = new DirObject('mydir')
            dir.addFile('a.txt', { name: 'a.txt', size: 10 }, 10)
            dir.addFile('b.txt', { name: 'b.txt', size: 20 }, 20)
            t.eq(dir.size, 2)
            t.eq(dir.file_count, 2)
            t.eq(dir.file_size, 30)
            t.eq(dir.total_size, 30)
            t.eq(dir.isFile('a.txt'), true)
            t.eq(dir.isDirectory('a.txt'), false)
            t.deepEq(dir.listEntries().sort(), ['a.txt', 'b.txt'])
        },
    },
    {
        name: 'DirObject.addDirectory accepts cydir ids and rejects non-dir ids',
        run(t) {
            const dir = new DirObject('mydir')
            const subDir = new ObjId(OBJ_TYPE_DIR, new Uint8Array(32).fill(9))
            dir.addDirectory('sub', subDir, 100)
            t.eq(dir.total_size, 100)
            t.eq(dir.file_count, 0)
            t.eq(dir.isDirectory('sub'), true)
            const wrong = new ObjId(OBJ_TYPE_FILE, new Uint8Array(32))
            t.throws(() => dir.addDirectory('bad', wrong, 0), 'InvalidParam')
        },
    },
    {
        name: 'DirObject genObjId is deterministic and produces a cydir id',
        run(t) {
            const dir = new DirObject('mydir')
            dir.content_obj.create_time = 100
            dir.content_obj.last_update_time = 200
            dir.addFile('a.txt', { name: 'a.txt' }, 10)
            const [id1, s1] = dir.genObjId()
            const [id2, s2] = dir.genObjId()
            t.eq(id1.equals(id2), true)
            t.eq(s1, s2)
            t.eq(id1.objType, OBJ_TYPE_DIR)
        },
    },
    {
        name: 'DirObject round-trips via toJSON / fromJSON for non-deriving fields',
        run(t) {
            const dir = new DirObject('mydir')
            dir.content_obj.create_time = 100
            dir.content_obj.last_update_time = 200
            dir.meta = { hint: 'test' }
            dir.addFile('a.txt', { name: 'a.txt' }, 10)
            const json = dir.toJSON()
            const back = DirObject.fromJSON(json)
            t.eq(back.content_obj.name, 'mydir')
            t.deepEq(back.meta, { hint: 'test' })
            t.eq(back.file_count, 1)
            t.eq(back.file_size, 10)
            t.eq(back.total_size, 10)
            t.eq(back.has('a.txt'), true)
        },
    },

    // ----- SimpleChunkList -----
    {
        name: 'SimpleChunkList genObjId mixes the total length into the resulting id',
        run(t) {
            const c1 = ChunkId.fromMix256Result(100, new Uint8Array(32).fill(0xa))
            const c2 = ChunkId.fromMix256Result(250, new Uint8Array(32).fill(0xb))
            const list = SimpleChunkList.fromChunkList([c1, c2])
            t.eq(list.total_size, 350)
            const [id, str] = list.genObjId()
            t.eq(id.objType, OBJ_TYPE_CHUNK_LIST_SIMPLE)
            const [decodedLen] = varintDecode(id.objHash, 0)
            t.eq(decodedLen, 350)
            t.deepEq(JSON.parse(str), [c1.toString(), c2.toString()])
        },
    },
    {
        name: 'SimpleChunkList rejects non-mix chunks (no length prefix)',
        run(t) {
            const plain = ChunkId.fromSha256Result(new Uint8Array(32))
            t.throws(() => SimpleChunkList.fromChunkList([plain]), 'InvalidParam')
        },
    },
    {
        name: 'SimpleChunkList.appendChunk updates total_size',
        run(t) {
            const list = new SimpleChunkList()
            list.appendChunk(ChunkId.fromMix256Result(7, new Uint8Array(32)))
            list.appendChunk(ChunkId.fromMix256Result(13, new Uint8Array(32)))
            t.eq(list.total_size, 20)
            t.eq(list.body.length, 2)
        },
    },
    {
        name: 'SimpleChunkList.fromJson parses an array of chunk strings',
        run(t) {
            const c = ChunkId.fromMix256Result(11, new Uint8Array(32).fill(0xc))
            const list = SimpleChunkList.fromJson(JSON.stringify([c.toString()]))
            t.eq(list.total_size, 11)
            t.eq(list.body.length, 1)
            t.eq(list.body[0].toString(), c.toString())
        },
    },

    // ----- RelationObject -----
    {
        name: 'RelationObject createByLinkData / getLinkData round-trip for sameAs',
        run(t) {
            const src = new ObjId('cyfile', new Uint8Array(32).fill(1))
            const tgt = new ObjId('cyfile', new Uint8Array(32).fill(2))
            const rel = RelationObject.createByLinkData(src, { kind: 'sameAs', target: tgt })
            t.eq(rel.relation, RELATION_TYPE_SAME)
            const link = rel.getLinkData()
            t.eq(link.kind, 'sameAs')
            if (link.kind === 'sameAs') t.eq(link.target.equals(tgt), true)
        },
    },
    {
        name: 'RelationObject createByLinkData / getLinkData round-trip for partOf',
        run(t) {
            const src = new ObjId('cyfile', new Uint8Array(32).fill(1))
            const tgt = new ObjId('cyfile', new Uint8Array(32).fill(2))
            const rel = RelationObject.createByLinkData(src, {
                kind: 'partOf',
                target: tgt,
                range: { start: 10, end: 20 },
            })
            t.eq(rel.relation, RELATION_TYPE_PART_OF)
            const link = rel.getLinkData()
            t.eq(link.kind, 'partOf')
            if (link.kind === 'partOf') {
                t.deepEq(link.range, { start: 10, end: 20 })
                t.eq(link.target.equals(tgt), true)
            }
        },
    },
    {
        name: 'RelationObject toJSON serializes source/target as strings and flattens body',
        run(t) {
            const src = new ObjId('cyfile', new Uint8Array(32).fill(1))
            const tgt = new ObjId('cyfile', new Uint8Array(32).fill(2))
            const rel = new RelationObject(src, RELATION_TYPE_SAME, tgt, { extra: 'meta' })
            rel.iat = 100
            const json = rel.toJSON() as Record<string, unknown>
            t.eq(json.source, src.toString())
            t.eq(json.target, tgt.toString())
            t.eq(json.relation, RELATION_TYPE_SAME)
            t.eq(json.extra, 'meta')
            t.eq(json.iat, 100)
            t.eq('exp' in json, false)
        },
    },
    {
        name: 'RelationObject genObjId yields a verifiable cyrel id',
        run(t) {
            const src = new ObjId('cyfile', new Uint8Array(32).fill(1))
            const tgt = new ObjId('cyfile', new Uint8Array(32).fill(2))
            const rel = RelationObject.createByLinkData(src, { kind: 'sameAs', target: tgt })
            const [id, str] = rel.genObjId()
            t.eq(id.objType, OBJ_TYPE_RELATION)
            t.eq(verifyNamedObject(id, JSON.parse(str)), true)
        },
    },
    {
        name: 'RelationObject getLinkData throws on invalid relation',
        run(t) {
            const src = new ObjId('cyfile', new Uint8Array(32).fill(1))
            const tgt = new ObjId('cyfile', new Uint8Array(32).fill(2))
            const rel = new RelationObject(src, 'bogus', tgt)
            t.throws(() => rel.getLinkData(), 'InvalidLink')
        },
    },

    // ----- KnownStandardObject -----
    {
        name: 'KnownStandardObject parses a FileObject from its serialized form',
        run(t) {
            const f = new FileObject('a.txt', 5, 'sha256:' + '00'.repeat(32))
            f.content_obj.create_time = 1
            f.content_obj.last_update_time = 2
            const [id, str] = f.genObjId()
            const known = KnownStandardObject.fromObjData(id, str)
            t.eq(known.kind, 'file')
            if (known.kind === 'file') {
                t.eq(known.obj.size, 5)
                t.eq(known.obj.content_obj.name, 'a.txt')
            }
            const children = KnownStandardObject.getChildObjs(known)
            t.eq(children.length, 1)
            t.eq(children[0].objId.objType, 'sha256')
        },
    },
    {
        name: 'KnownStandardObject parses a DirObject and exposes its child entries',
        run(t) {
            const dir = new DirObject('mydir')
            dir.content_obj.create_time = 1
            dir.content_obj.last_update_time = 2
            dir.addFile('a.txt', { name: 'a.txt' }, 10)
            const json = dir.toJSON()
            const id = new ObjId(OBJ_TYPE_DIR, new Uint8Array(32))
            const known = KnownStandardObject.fromObjData(id, JSON.stringify(json))
            t.eq(known.kind, 'dir')
            if (known.kind === 'dir') t.eq(known.obj.has('a.txt'), true)
            const children = KnownStandardObject.getChildObjs(known)
            t.eq(children.length, 1)
        },
    },
    {
        name: 'KnownStandardObject parses a SimpleChunkList',
        run(t) {
            const c = ChunkId.fromMix256Result(11, new Uint8Array(32).fill(0xc))
            const objStr = JSON.stringify([c.toString()])
            const id = new ObjId(OBJ_TYPE_CHUNK_LIST_SIMPLE, new Uint8Array(32))
            const known = KnownStandardObject.fromObjData(id, objStr)
            t.eq(known.kind, 'chunkList')
            const children = KnownStandardObject.getChildObjs(known)
            t.eq(children.length, 1)
            t.eq(children[0].objId.objType, 'mix256')
        },
    },
    {
        name: 'KnownStandardObject throws for unknown object types',
        run(t) {
            const id = new ObjId('unknown-type', new Uint8Array(32))
            t.throws(() => KnownStandardObject.fromObjData(id, '{}'), 'InvalidParam')
        },
    },

    // ----- Rust-generated fixture: protocol-correctness verification -----
    //
    // Loads tests/ndn_object.json (produced by the Rust ndn-lib reference
    // implementation) and verifies that, for every (objid, objjson) pair,
    // SHA-256(canonical(objjson)) under our TypeScript implementation
    // reproduces the exact ObjId that Rust produced. This is bit-for-bit
    // protocol compatibility, not just behavioural parity.
    ...buildRustFixtureCases(),
]

function buildRustFixtureCases(): NdnTypesTestCase[] {
    if (!Array.isArray(ndnObjectFixture)) {
        return [
            {
                name: 'rust fixture: tests/ndn_object.json must be an array',
                run() {
                    throw new Error(
                        `expected ndn_object.json to be an array, got ${typeof ndnObjectFixture}`,
                    )
                },
            },
        ]
    }

    const cases: NdnTypesTestCase[] = []

    // Aggregate "all entries verify" check — fast feedback when bulk-loading.
    cases.push({
        name: 'rust fixture: every entry verifies via verifyNamedObject',
        run(t) {
            t.truthy(
                ndnObjectFixture.length > 0,
                'fixture must contain at least one entry',
            )
            for (const raw of ndnObjectFixture) {
                const entry = raw as { objid?: unknown; objjson?: unknown }
                t.truthy(
                    typeof entry.objid === 'string',
                    `entry missing objid: ${JSON.stringify(entry)}`,
                )
                t.truthy(
                    entry.objjson != null && typeof entry.objjson === 'object',
                    `entry missing objjson: ${JSON.stringify(entry)}`,
                )
                const expected = ObjId.fromString(entry.objid as string)
                const ok = verifyNamedObject(expected, entry.objjson)
                if (!ok) {
                    // Recompute to surface the actual hash for easier triage.
                    const [actual, canonical] = buildNamedObjectByJson(
                        expected.objType,
                        entry.objjson,
                    )
                    throw new Error(
                        `rust fixture mismatch for ${expected.toString()}\n` +
                            `  computed: ${actual.toString()}\n` +
                            `  canonical: ${canonical}`,
                    )
                }
            }
        },
    })

    // Per-entry case so jest reports each ObjId individually on failure.
    for (const raw of ndnObjectFixture) {
        const entry = raw as { objid?: unknown; objjson?: unknown }
        if (typeof entry.objid !== 'string' || entry.objjson == null) continue
        const objIdStr = entry.objid
        const objJson = entry.objjson
        cases.push({
            name: `rust fixture: ${objIdStr}`,
            run(t) {
                const expected = ObjId.fromString(objIdStr)
                const [actual, canonical] = buildNamedObjectByJson(
                    expected.objType,
                    objJson,
                )
                t.eq(
                    actual.toString(),
                    expected.toString(),
                    `canonical=${canonical}`,
                )
                t.eq(verifyNamedObject(expected, objJson), true)
            },
        })
    }

    return cases
}

// ============================================================
// Standalone runner (used by the browser test page)
// ============================================================

export interface NdnTypesRunResult {
    name: string
    ok: boolean
    error?: string
}

export function runNdnTypesCases(
    cases: NdnTypesTestCase[] = NDN_TYPES_TEST_CASES,
    tap: Tap = defaultTap,
): { ok: boolean; total: number; failed: number; results: NdnTypesRunResult[] } {
    const results: NdnTypesRunResult[] = []
    let failed = 0
    for (const c of cases) {
        try {
            c.run(tap)
            results.push({ name: c.name, ok: true })
        } catch (e) {
            failed++
            results.push({
                name: c.name,
                ok: false,
                error: (e as Error)?.message ?? String(e),
            })
        }
    }
    return { ok: failed === 0, total: cases.length, failed, results }
}
