// Generated by scripts/generate-cli-version.mjs. Do not edit.
export const PACKAGE_VERSION = '0.7.117'
export const TOOL_VERSION = PACKAGE_VERSION
export const SDK_VERSION = PACKAGE_VERSION
export const PROTOCOL_VERSION = '1'
