// TypeScript port of cyfs-ndn/src/ndn-lib (Rust) NamedObject definitions.
//
// This file mirrors the data layout and on-the-wire JSON encoding of:
//   - ObjId / ChunkId / HashMethod / ChunkType
//   - NamedObject trait + helpers (build_obj_id, build_named_object_by_json,
//     verify_named_object, load_named_obj)
//   - BaseContentObject / FileObject / PathObject / InclusionProof
//   - SimpleObjectMap / SimpleMapItem / DirObject
//   - SimpleChunkList
//   - RelationObject
//
// The canonical JSON form (sorted keys, compact) and SHA-256-based ObjId
// derivation are the same as the Rust implementation, so ObjIds generated
// here are byte-equivalent to those generated by ndn-lib for the same input.

import jsSHA from 'jssha'

// ============================================================
// Errors
// ============================================================

export type NdnErrorKind =
    | 'Internal'
    | 'InvalidId'
    | 'InvalidLink'
    | 'NotFound'
    | 'NotReady'
    | 'AlreadyExists'
    | 'VerifyError'
    | 'IoError'
    | 'DbError'
    | 'InComplete'
    | 'RemoteError'
    | 'DecodeError'
    | 'OffsetTooLarge'
    | 'InvalidObjType'
    | 'InvalidData'
    | 'InvalidParam'
    | 'InvalidState'
    | 'PermissionDenied'
    | 'Unsupported'

export class NdnError extends Error {
    public readonly kind: NdnErrorKind
    constructor(kind: NdnErrorKind, message: string) {
        super(`${kind}: ${message}`)
        this.kind = kind
        this.name = 'NdnError'
    }
}

// ============================================================
// Object type constants (from ndn-lib/src/lib.rs)
// ============================================================

export const OBJ_TYPE_FILE = 'cyfile'
export const OBJ_TYPE_DIR = 'cydir'
export const OBJ_TYPE_MSG = 'cymsg'
export const OBJ_TYPE_MSG_RECE = 'cymsgr'
export const OBJ_TYPE_PATH = 'cypath'
export const OBJ_TYPE_INCLUSION_PROOF = 'cyinc'
export const OBJ_TYPE_RELATION = 'cyrel'
export const OBJ_TYPE_ACTION = 'cyact'
export const OBJ_TYPE_PACK = 'cypack'

export const OBJ_TYPE_TRIE = 'cytrie'
export const OBJ_TYPE_TRIE_SIMPLE = 'cytrie-s'

export const OBJ_TYPE_OBJMAP = 'cymap-mtp'
export const OBJ_TYPE_OBJMAP_SIMPLE = 'cymap'

export const OBJ_TYPE_LIST = 'cylist-mtree'
export const OBJ_TYPE_LIST_SIMPLE = 'cylist'

export const OBJ_TYPE_CHUNK_LIST = 'cl'
export const OBJ_TYPE_CHUNK_LIST_SIMPLE = 'clist'
export const OBJ_TYPE_CHUNK_LIST_FIX_SIZE = 'clist-fix'
export const OBJ_TYPE_CHUNK_LIST_SIMPLE_FIX_SIZE = 'cl-sf'

export const OBJ_TYPE_PKG = 'pkg'

export const RELATION_TYPE_SAME = 'same'
export const RELATION_TYPE_PART_OF = 'part_of'

// ============================================================
// Low-level encoding helpers
// ============================================================

const HEX_CHARS = '0123456789abcdef'

export function bytesToHex(bytes: Uint8Array): string {
    let s = ''
    for (let i = 0; i < bytes.length; i++) {
        const b = bytes[i]
        s += HEX_CHARS[(b >>> 4) & 0xf]
        s += HEX_CHARS[b & 0xf]
    }
    return s
}

export function hexToBytes(hex: string): Uint8Array {
    if (hex.length % 2 !== 0) {
        throw new NdnError('InvalidId', `invalid hex length: ${hex.length}`)
    }
    const out = new Uint8Array(hex.length / 2)
    for (let i = 0; i < out.length; i++) {
        const hi = HEX_CHARS.indexOf(hex[i * 2].toLowerCase())
        const lo = HEX_CHARS.indexOf(hex[i * 2 + 1].toLowerCase())
        if (hi < 0 || lo < 0) {
            throw new NdnError('InvalidId', `invalid hex char at offset ${i * 2}`)
        }
        out[i] = (hi << 4) | lo
    }
    return out
}

// Base32 RFC4648 lowercase, no padding (matches base32::Alphabet::Rfc4648Lower
// {padding: false} used by ndn-lib).
const BASE32_ALPHABET = 'abcdefghijklmnopqrstuvwxyz234567'

export function base32Encode(bytes: Uint8Array): string {
    let bits = 0
    let value = 0
    let out = ''
    for (let i = 0; i < bytes.length; i++) {
        value = (value << 8) | bytes[i]
        bits += 8
        while (bits >= 5) {
            bits -= 5
            out += BASE32_ALPHABET[(value >>> bits) & 0x1f]
        }
    }
    if (bits > 0) {
        out += BASE32_ALPHABET[(value << (5 - bits)) & 0x1f]
    }
    return out
}

export function base32Decode(str: string): Uint8Array {
    const lower = str.toLowerCase()
    let bits = 0
    let value = 0
    const out: number[] = []
    for (let i = 0; i < lower.length; i++) {
        const ch = lower[i]
        const idx = BASE32_ALPHABET.indexOf(ch)
        if (idx < 0) {
            throw new NdnError('InvalidId', `invalid base32 char '${ch}' at ${i}`)
        }
        value = (value << 5) | idx
        bits += 5
        if (bits >= 8) {
            bits -= 8
            out.push((value >>> bits) & 0xff)
        }
    }
    return new Uint8Array(out)
}

// Unsigned varint (LEB128) encoding, matches `unsigned_varint` crate used by
// ndn-lib for length encoding inside ChunkId/ChunkList.
export function varintEncode(value: number): Uint8Array {
    if (!Number.isFinite(value) || value < 0) {
        throw new NdnError('InvalidParam', `varint must be non-negative finite: ${value}`)
    }
    if (!Number.isSafeInteger(value)) {
        throw new NdnError('InvalidParam', `varint exceeds safe integer range: ${value}`)
    }
    const out: number[] = []
    let v = value
    while (v >= 0x80) {
        out.push((v & 0x7f) | 0x80)
        v = Math.floor(v / 128)
    }
    out.push(v & 0x7f)
    return new Uint8Array(out)
}

// Returns [value, bytes_consumed]
export function varintDecode(bytes: Uint8Array, offset: number = 0): [number, number] {
    let result = 0
    let shiftMul = 1
    let i = offset
    let consumed = 0
    while (i < bytes.length) {
        const b = bytes[i++]
        consumed++
        const part = b & 0x7f
        // result += part * 2^(7*consumed-7)
        result += part * shiftMul
        if (!Number.isSafeInteger(result)) {
            throw new NdnError('InvalidData', 'varint exceeds safe integer range')
        }
        if ((b & 0x80) === 0) {
            return [result, consumed]
        }
        shiftMul *= 128
        if (consumed > 10) {
            throw new NdnError('InvalidData', 'varint too long')
        }
    }
    throw new NdnError('InvalidData', 'varint truncated')
}

// ============================================================
// SHA-256 / canonical JSON
// ============================================================

export function sha256Bytes(data: Uint8Array): Uint8Array {
    const sha = new jsSHA('SHA-256', 'UINT8ARRAY')
    sha.update(data)
    return sha.getHash('UINT8ARRAY')
}

export function sha256Utf8(text: string): Uint8Array {
    const sha = new jsSHA('SHA-256', 'TEXT', { encoding: 'UTF8' })
    sha.update(text)
    return sha.getHash('UINT8ARRAY')
}

/**
 * Recursively sort object keys (BTreeMap-like). Arrays preserve order.
 * This matches the `stabilize_json` helper in ndn-lib so that the resulting
 * JSON string (and thus the SHA-256-derived ObjId) is deterministic.
 */
export function canonicalizeJson(value: any): any {
    if (value === null || typeof value !== 'object') return value
    if (Array.isArray(value)) return value.map(canonicalizeJson)
    const keys = Object.keys(value).sort()
    const result: Record<string, any> = {}
    for (const k of keys) {
        result[k] = canonicalizeJson(value[k])
    }
    return result
}

export function toCanonicalJsonString(value: any): string {
    return JSON.stringify(canonicalizeJson(value))
}

// ============================================================
// HashMethod
// ============================================================

export const DEFAULT_HASH_METHOD = 'sha256'

export type HashMethod =
    | 'sha256'
    | 'sha512'
    | 'qcid'
    | 'blake2s256'
    | 'keccak256'

export const HashMethod = {
    Sha256: 'sha256' as HashMethod,
    Sha512: 'sha512' as HashMethod,
    QCID: 'qcid' as HashMethod,
    Blake2s256: 'blake2s256' as HashMethod,
    Keccak256: 'keccak256' as HashMethod,

    hashResultSize(method: HashMethod): number {
        switch (method) {
            case 'sha256': return 32
            case 'sha512': return 64
            case 'qcid': return 32
            case 'blake2s256': return 32
            case 'keccak256': return 32
        }
    },

    /** parse(s) -> [HashMethod, isMix]; "mix256" -> [Sha256, true]. */
    parse(s: string): [HashMethod, boolean] {
        const isMix = s.startsWith('mix')
        const method = HashMethod.fromString(s)
        return [method, isMix]
    },

    fromString(s: string): HashMethod {
        switch (s) {
            case 'sha256':
            case 'mix256':
                return 'sha256'
            case 'sha512':
            case 'mix512':
                return 'sha512'
            case 'qcid':
            case 'mixqcid':
                return 'qcid'
            case 'blake2s256':
            case 'mixblake2s256':
                return 'blake2s256'
            case 'keccak256':
            case 'mixkeccak256':
                return 'keccak256'
            default:
                throw new NdnError('InvalidData', `Invalid hash method: ${s}`)
        }
    },
}

// ============================================================
// ChunkType
// ============================================================

export type ChunkTypeStr =
    | 'sha256'
    | 'mix256'
    | 'sha512'
    | 'mix512'
    | 'qcid'
    | 'blake2s256'
    | 'mixblake2s256'
    | 'keccak256'
    | 'mixkeccak256'
    | string // Unknown variants are passed through.

export const ChunkType = {
    Sha256: 'sha256' as ChunkTypeStr,
    Mix256: 'mix256' as ChunkTypeStr,
    Sha512: 'sha512' as ChunkTypeStr,
    Mix512: 'mix512' as ChunkTypeStr,
    QCID: 'qcid' as ChunkTypeStr,
    Blake2s256: 'blake2s256' as ChunkTypeStr,
    MixBlake2s256: 'mixblake2s256' as ChunkTypeStr,
    Keccak256: 'keccak256' as ChunkTypeStr,
    MixKeccak256: 'mixkeccak256' as ChunkTypeStr,

    isChunkType(typeStr: string): boolean {
        switch (typeStr) {
            case 'sha256':
            case 'mix256':
            case 'sha512':
            case 'mix512':
            case 'qcid':
            case 'blake2s256':
            case 'mixblake2s256':
            case 'keccak256':
            case 'mixkeccak256':
                return true
            default:
                return false
        }
    },

    isMix(typeStr: ChunkTypeStr): boolean {
        switch (typeStr) {
            case 'mix256':
            case 'mix512':
            case 'mixblake2s256':
            case 'mixkeccak256':
            case 'qcid':
                return true
            default:
                return false
        }
    },

    fromHashType(hashType: HashMethod, isMix: boolean): ChunkTypeStr {
        switch (hashType) {
            case 'sha256': return isMix ? 'mix256' : 'sha256'
            case 'sha512': return isMix ? 'mix512' : 'sha512'
            case 'qcid':
                if (!isMix) {
                    throw new NdnError('InvalidObjType', 'QCID must be mix hash')
                }
                return 'qcid'
            case 'blake2s256': return isMix ? 'mixblake2s256' : 'blake2s256'
            case 'keccak256': return isMix ? 'mixkeccak256' : 'keccak256'
        }
    },

    toHashMethod(typeStr: ChunkTypeStr): HashMethod {
        switch (typeStr) {
            case 'sha256':
            case 'mix256':
                return 'sha256'
            case 'sha512':
            case 'mix512':
                return 'sha512'
            case 'qcid':
                return 'qcid'
            case 'blake2s256':
            case 'mixblake2s256':
                return 'blake2s256'
            case 'keccak256':
            case 'mixkeccak256':
                return 'keccak256'
            default:
                throw new NdnError('InvalidObjType', `invalid chunk type: ${typeStr}`)
        }
    },
}

// ============================================================
// ObjId
// ============================================================

/**
 * ObjId (Object Identifier) - mirrors ndn_lib::ObjId.
 *
 * On-wire JSON form is a string `${objType}:${hex(objHash)}`.
 * Display / hostname form is base32-lowercase of `objType + ":" + objHash`.
 */
export class ObjId {
    public objType: string
    public objHash: Uint8Array

    constructor(objType: string, objHash: Uint8Array) {
        this.objType = objType
        this.objHash = objHash
    }

    /** Parse from base32 (no separator) or `obj_type:hex_hash`. */
    static fromString(s: string): ObjId {
        const parts = s.split(':')
        if (parts.length === 1) {
            const decoded = base32Decode(parts[0])
            // Find first ':' in decoded bytes.
            let pos = -1
            for (let i = 0; i < decoded.length; i++) {
                if (decoded[i] === 0x3a /* ':' */) {
                    pos = i
                    break
                }
            }
            if (pos < 0) {
                throw new NdnError('InvalidId', "separator ':' not found")
            }
            const objType = utf8Decode(decoded.subarray(0, pos))
            const objHash = decoded.slice(pos + 1)
            return new ObjId(objType, objHash)
        } else if (parts.length === 2) {
            return new ObjId(parts[0], hexToBytes(parts[1]))
        } else {
            throw new NdnError('InvalidId', s)
        }
    }

    static fromBytes(bytes: Uint8Array): ObjId {
        if (bytes.length < 3) {
            throw new NdnError('InvalidId', 'objid bytes too short')
        }
        let pos = -1
        for (let i = 0; i < bytes.length; i++) {
            if (bytes[i] === 0x3a) {
                pos = i
                break
            }
        }
        if (pos < 0) {
            throw new NdnError('InvalidId', "separator ':' not found")
        }
        const objType = utf8Decode(bytes.subarray(0, pos))
        const objHash = bytes.slice(pos + 1)
        return new ObjId(objType, objHash)
    }

    static fromValue(v: unknown): ObjId {
        if (typeof v === 'string') {
            return ObjId.fromString(v)
        }
        throw new NdnError('InvalidData', 'ObjId MUST be string')
    }

    static fromHostname(hostname: string): ObjId {
        const first = hostname.split('.')[0]
        return ObjId.fromString(first)
    }

    /**
     * Try to extract an ObjId from an NDN-style path. Returns the ObjId and
     * the optional remaining sub-path (with leading '/'), or null if no part
     * of the path parses as an ObjId.
     */
    static fromPath(path: string): { objId: ObjId; subPath: string | null } {
        const parts = path.split('/')
        for (let i = 0; i < parts.length; i++) {
            const part = parts[i]
            if (part.length === 0) continue
            try {
                const objId = ObjId.fromString(part)
                if (i < parts.length - 1) {
                    return { objId, subPath: '/' + parts.slice(i + 1).join('/') }
                }
                return { objId, subPath: null }
            } catch {
                // keep trying
            }
        }
        throw new NdnError('InvalidId', `no objid found in path: ${path}`)
    }

    /** Construct an ObjId from a precomputed hash. */
    static fromRaw(objType: string, hashValue: Uint8Array): ObjId {
        return new ObjId(objType, hashValue)
    }

    isChunk(): boolean {
        return ChunkType.isChunkType(this.objType)
    }

    isChunkList(): boolean {
        return this.objType === OBJ_TYPE_CHUNK_LIST_SIMPLE
    }

    isJson(): boolean {
        if (this.isChunk() || this.isContainer()) return false
        return this.objType !== OBJ_TYPE_PACK
    }

    isDirObject(): boolean {
        return this.objType === OBJ_TYPE_DIR
    }

    isFileObject(): boolean {
        return this.objType === OBJ_TYPE_FILE
    }

    isContainer(): boolean {
        switch (this.objType) {
            case OBJ_TYPE_DIR:
            case OBJ_TYPE_TRIE:
            case OBJ_TYPE_TRIE_SIMPLE:
            case OBJ_TYPE_OBJMAP:
            case OBJ_TYPE_OBJMAP_SIMPLE:
            case OBJ_TYPE_LIST:
            case OBJ_TYPE_LIST_SIMPLE:
            case OBJ_TYPE_CHUNK_LIST:
            case OBJ_TYPE_CHUNK_LIST_SIMPLE:
            case OBJ_TYPE_CHUNK_LIST_FIX_SIZE:
            case OBJ_TYPE_CHUNK_LIST_SIMPLE_FIX_SIZE:
                return true
            default:
                return false
        }
    }

    isBigContainer(): boolean {
        switch (this.objType) {
            case OBJ_TYPE_TRIE:
            case OBJ_TYPE_OBJMAP:
            case OBJ_TYPE_LIST:
            case OBJ_TYPE_CHUNK_LIST:
            case OBJ_TYPE_CHUNK_LIST_FIX_SIZE:
                return true
            default:
                return false
        }
    }

    /** `${obj_type}:${hex(obj_hash)}` form. */
    toString(): string {
        return `${this.objType}:${bytesToHex(this.objHash)}`
    }

    toFilename(): string {
        return `${bytesToHex(this.objHash)}.${this.objType}`
    }

    toBase32(): string {
        return base32Encode(this.toBytes())
    }

    toBytes(): Uint8Array {
        const typeBytes = utf8Encode(this.objType)
        const out = new Uint8Array(typeBytes.length + 1 + this.objHash.length)
        out.set(typeBytes, 0)
        out[typeBytes.length] = 0x3a
        out.set(this.objHash, typeBytes.length + 1)
        return out
    }

    /** Used for JSON.stringify -> serialized as the `${type}:${hex}` string. */
    toJSON(): string {
        return this.toString()
    }

    equals(other: ObjId): boolean {
        if (this.objType !== other.objType) return false
        if (this.objHash.length !== other.objHash.length) return false
        for (let i = 0; i < this.objHash.length; i++) {
            if (this.objHash[i] !== other.objHash[i]) return false
        }
        return true
    }
}

// ============================================================
// ChunkId
// ============================================================

/**
 * ChunkId - mirrors ndn_lib::ChunkId. Wire format is identical to ObjId
 * (`${chunk_type}:${hex(hash_result)}`); for "mix*" types the hash bytes
 * begin with a varint-encoded data length.
 */
export class ChunkId {
    public chunkType: ChunkTypeStr
    public hashResult: Uint8Array

    constructor(chunkType: ChunkTypeStr, hashResult: Uint8Array) {
        this.chunkType = chunkType
        this.hashResult = hashResult
    }

    static defaultChunkType(): ChunkTypeStr {
        return 'mix256'
    }

    static fromString(s: string): ChunkId {
        const objId = ObjId.fromString(s)
        if (!objId.isChunk()) {
            throw new NdnError('InvalidId', `invalid chunk id: ${s}`)
        }
        return new ChunkId(objId.objType, objId.objHash)
    }

    static fromObjId(objId: ObjId): ChunkId {
        return new ChunkId(objId.objType, new Uint8Array(objId.objHash))
    }

    static fromBytes(bytes: Uint8Array): ChunkId {
        const obj = ObjId.fromBytes(bytes)
        return new ChunkId(obj.objType, obj.objHash)
    }

    /** Construct from raw hash result, no length encoding. */
    static fromHashResult(hashResult: Uint8Array, chunkType: ChunkTypeStr): ChunkId {
        return new ChunkId(chunkType, new Uint8Array(hashResult))
    }

    /** Construct mix-style ChunkId by prepending varint(length) to hash. */
    static fromMixHashResult(
        dataLength: number,
        hashResult: Uint8Array,
        chunkType: ChunkTypeStr,
    ): ChunkId {
        return new ChunkId(chunkType, ChunkId.mixLengthAndHashResult(dataLength, hashResult))
    }

    static fromMixHashResultByHashMethod(
        dataLength: number,
        hashResult: Uint8Array,
        hashMethod: HashMethod,
    ): ChunkId {
        const chunkType = ChunkType.fromHashType(hashMethod, true)
        return new ChunkId(chunkType, ChunkId.mixLengthAndHashResult(dataLength, hashResult))
    }

    static fromSha256Result(hashResult: Uint8Array): ChunkId {
        return new ChunkId('sha256', new Uint8Array(hashResult))
    }

    static fromMix256Result(dataLength: number, hashResult: Uint8Array): ChunkId {
        return new ChunkId('mix256', ChunkId.mixLengthAndHashResult(dataLength, hashResult))
    }

    static mixLengthAndHashResult(dataLength: number, hashResult: Uint8Array): Uint8Array {
        const lenBytes = varintEncode(dataLength)
        const out = new Uint8Array(lenBytes.length + hashResult.length)
        out.set(lenBytes, 0)
        out.set(hashResult, lenBytes.length)
        return out
    }

    toObjId(): ObjId {
        return new ObjId(this.chunkType, new Uint8Array(this.hashResult))
    }

    toString(): string {
        return `${this.chunkType}:${bytesToHex(this.hashResult)}`
    }

    toBase32(): string {
        const typeBytes = utf8Encode(this.chunkType)
        const buf = new Uint8Array(typeBytes.length + 1 + this.hashResult.length)
        buf.set(typeBytes, 0)
        buf[typeBytes.length] = 0x3a
        buf.set(this.hashResult, typeBytes.length + 1)
        return base32Encode(buf)
    }

    toDidString(): string {
        return `did:${this.chunkType}:${bytesToHex(this.hashResult)}`
    }

    toBytes(): Uint8Array {
        return this.toObjId().toBytes()
    }

    toJSON(): string {
        return this.toString()
    }

    /** For mix-* types, return the data length encoded in the prefix. */
    getLength(): number | null {
        if (this.hashResult.length === 0) return null
        if (!ChunkType.isMix(this.chunkType)) return null
        try {
            const [len] = varintDecode(this.hashResult, 0)
            return len
        } catch {
            return null
        }
    }

    equalsHash(hashBytes: Uint8Array): boolean {
        if (this.hashResult.length !== hashBytes.length) return false
        for (let i = 0; i < this.hashResult.length; i++) {
            if (this.hashResult[i] !== hashBytes[i]) return false
        }
        return true
    }
}

// ============================================================
// NamedObject base + helpers
// ============================================================

/**
 * Anything that can be hashed into an ObjId. Implementations need only
 * provide getObjType() and toJSON() (the JSON-serializable form). The
 * default genObjId() then derives the ObjId from canonical JSON.
 */
export interface NamedObject {
    getObjType(): string
    toJSON(): unknown
    genObjId(): [ObjId, string]
}

export abstract class NamedObjectBase implements NamedObject {
    abstract getObjType(): string
    abstract toJSON(): unknown
    genObjId(): [ObjId, string] {
        return buildNamedObjectByJson(this.getObjType(), this.toJSON())
    }
}

/** SHA-256-based ObjId derivation: matches build_obj_id() in ndn-lib. */
export function buildObjId(objType: string, objJsonStr: string): ObjId {
    const hash = sha256Utf8(objJsonStr)
    return ObjId.fromRaw(objType, hash)
}

/**
 * Canonicalize the JSON value (recursive sort), serialize, then derive ObjId.
 * Matches build_named_object_by_json() in ndn-lib.
 */
export function buildNamedObjectByJson(
    objType: string,
    jsonValue: unknown,
): [ObjId, string] {
    const jsonStr = toCanonicalJsonString(jsonValue)
    const objId = buildObjId(objType, jsonStr)
    return [objId, jsonStr]
}

/** Verify that the JSON canonical hash equals the expected ObjId. */
export function verifyNamedObject(objId: ObjId, jsonValue: unknown): boolean {
    const [objId2] = buildNamedObjectByJson(objId.objType, jsonValue)
    return objId.equals(objId2)
}

export function verifyNamedObjectFromStr(objId: ObjId, objStr: string): unknown {
    let parsed: unknown
    try {
        parsed = JSON.parse(objStr)
    } catch (e) {
        throw new NdnError('InvalidId', `failed to parse obj_str: ${(e as Error).message}`)
    }
    if (!verifyNamedObject(objId, parsed)) {
        throw new NdnError('InvalidId', `verify named object failed: ${objStr}`)
    }
    return parsed
}

/**
 * Parse an obj-data-string. The Rust version also accepts JWT, but here we
 * just look at whether the string starts with `{`. JWT decoding is left to
 * the caller (it depends on signature verification anyway).
 */
export function loadNamedObjectFromObjStr(objStr: string): unknown {
    if (objStr.indexOf('{') >= 0) {
        try {
            return JSON.parse(objStr)
        } catch (e) {
            throw new NdnError('InvalidId', `failed to parse obj_str: ${(e as Error).message}`)
        }
    }
    throw new NdnError(
        'Unsupported',
        'JWT-encoded named objects are not supported in this TypeScript port',
    )
}

export function loadNamedObj<T = unknown>(objStr: string): T {
    return loadNamedObjectFromObjStr(objStr) as T
}

export function loadNamedObjAndVerify<T = unknown>(objId: ObjId, objStr: string): T {
    const parsed = loadNamedObjectFromObjStr(objStr)
    if (!verifyNamedObject(objId, parsed)) {
        throw new NdnError('InvalidId', `verify named object failed for obj_id: ${objId.toString()}`)
    }
    return parsed as T
}

/** Walk a JSON value via a `/foo/bar/0/baz` path and parse it as ObjId. */
export function extractObjIdByPath(jsonValue: unknown, path: string): ObjId {
    const parts = path.split('/').filter(p => p.length > 0)
    let cursor: any = jsonValue
    for (const p of parts) {
        if (cursor == null) {
            throw new NdnError('InvalidParam', `objid path not found: ${path}`)
        }
        if (Array.isArray(cursor)) {
            const idx = Number(p)
            if (!Number.isInteger(idx) || idx < 0 || idx >= cursor.length) {
                throw new NdnError('InvalidParam', `objid path not found: ${path}`)
            }
            cursor = cursor[idx]
        } else if (typeof cursor === 'object') {
            if (!(p in cursor)) {
                throw new NdnError('InvalidParam', `objid path not found: ${path}`)
            }
            cursor = cursor[p]
        } else {
            throw new NdnError('InvalidParam', `objid path not found: ${path}`)
        }
    }
    try {
        return ObjId.fromValue(cursor)
    } catch (e) {
        throw new NdnError('InvalidData', `invalid objid at path ${path}: ${(e as Error).message}`)
    }
}

// ============================================================
// BaseContentObject (from base_content.rs)
// ============================================================

export type DID = string

export interface BaseContentObjectFields {
    did?: DID | null
    name?: string
    author?: string
    owner?: DID
    create_time?: number
    last_update_time?: number
    copyright?: string | null
    tags?: string[]
    categories?: string[]
    base_on?: ObjId | null
    directory?: Record<string, unknown>
    references?: Record<string, unknown>
    exp?: number
}

/**
 * Mirrors ndn-lib BaseContentObject. Optional/empty fields are skipped on
 * serialization (matching `skip_serializing_if`) so that ObjIds derived from
 * a TS instance match those derived from the equivalent Rust value.
 */
export class BaseContentObject {
    public did: DID | null
    public name: string
    public author: string
    public owner: DID
    public create_time: number
    public last_update_time: number
    public copyright: string | null
    public tags: string[]
    public categories: string[]
    public base_on: ObjId | null
    public directory: Record<string, unknown>
    public references: Record<string, unknown>
    public exp: number

    constructor(fields: BaseContentObjectFields = {}) {
        this.did = fields.did ?? null
        this.name = fields.name ?? ''
        this.author = fields.author ?? ''
        this.owner = fields.owner ?? ''
        this.create_time = fields.create_time ?? 0
        this.last_update_time = fields.last_update_time ?? 0
        this.copyright = fields.copyright ?? null
        this.tags = fields.tags ?? []
        this.categories = fields.categories ?? []
        this.base_on = fields.base_on ?? null
        this.directory = fields.directory ?? {}
        this.references = fields.references ?? {}
        this.exp = fields.exp ?? 0
    }

    /** Build the JSON object using the same skip rules as Rust serde. */
    toJSON(): Record<string, unknown> {
        const out: Record<string, unknown> = {}
        if (this.did != null) out.did = this.did
        if (this.name.length > 0) out.name = this.name
        if (this.author.length > 0) out.author = this.author
        if (this.owner.length > 0) out.owner = this.owner
        out.create_time = this.create_time
        out.last_update_time = this.last_update_time
        if (this.copyright != null) out.copyright = this.copyright
        if (this.tags.length > 0) out.tags = this.tags
        if (this.categories.length > 0) out.categories = this.categories
        if (this.base_on != null) out.base_on = this.base_on.toString()
        if (Object.keys(this.directory).length > 0) out.directory = this.directory
        if (Object.keys(this.references).length > 0) out.references = this.references
        if (this.exp !== 0) out.exp = this.exp
        return out
    }
}

function nowSeconds(): number {
    return Math.floor(Date.now() / 1000)
}

// ============================================================
// FileObject / PathObject (from fileobj.rs)
// ============================================================

export class FileObject extends NamedObjectBase {
    public content_obj: BaseContentObject
    public size: number
    /** chunkid or chunklist id, or empty string. */
    public content: string
    /** Free-form metadata. Flattened into the object root on serialization. */
    public meta: Record<string, unknown>

    constructor(name: string, size: number, content: string) {
        super()
        this.content_obj = new BaseContentObject({ name })
        this.size = size
        this.content = content
        this.meta = {}
    }

    static fromJSON(value: Record<string, unknown>): FileObject {
        const file = new FileObject('', 0, '')
        const base: BaseContentObjectFields = {}
        const meta: Record<string, unknown> = {}
        const baseKeys = new Set([
            'did', 'name', 'author', 'owner', 'create_time', 'last_update_time',
            'copyright', 'tags', 'categories', 'base_on', 'directory', 'references', 'exp',
        ])
        for (const [k, v] of Object.entries(value)) {
            if (k === 'size') {
                file.size = (v as number) ?? 0
            } else if (k === 'content') {
                file.content = (v as string) ?? ''
            } else if (baseKeys.has(k)) {
                if (k === 'base_on' && typeof v === 'string') {
                    base.base_on = ObjId.fromString(v)
                } else {
                    (base as any)[k] = v
                }
            } else {
                meta[k] = v
            }
        }
        file.content_obj = new BaseContentObject(base)
        file.meta = meta
        return file
    }

    getObjType(): string {
        return OBJ_TYPE_FILE
    }

    toJSON(): Record<string, unknown> {
        const out: Record<string, unknown> = { ...this.content_obj.toJSON() }
        if (this.size !== 0) out.size = this.size
        if (this.content.length > 0) out.content = this.content
        for (const [k, v] of Object.entries(this.meta)) {
            out[k] = v
        }
        return out
    }
}

export class PathObject extends NamedObjectBase {
    public path: string
    public uptime: number
    public target: ObjId
    public exp: number

    constructor(path: string, target: ObjId, uptime?: number, exp?: number) {
        super()
        const now = nowSeconds()
        this.path = path
        this.target = target
        this.uptime = uptime ?? now
        this.exp = exp ?? now + 3600 * 24 * 365 * 3
    }

    static fromJSON(value: Record<string, unknown>): PathObject {
        const path = String(value.path ?? '')
        const target = ObjId.fromString(String(value.target ?? ''))
        const uptime = Number(value.uptime ?? 0)
        const exp = Number(value.exp ?? 0)
        return new PathObject(path, target, uptime, exp)
    }

    getObjType(): string {
        return OBJ_TYPE_PATH
    }

    toJSON(): Record<string, unknown> {
        return {
            path: this.path,
            uptime: this.uptime,
            target: this.target.toString(),
            exp: this.exp,
        }
    }
}

// ============================================================
// InclusionProof (from base_content.rs)
// ============================================================

export class InclusionProof extends NamedObjectBase {
    public content_id: string
    public content_obj: unknown
    public curator: DID
    public editor: string[]
    public meta: unknown
    public rank: number
    public collection: string[]
    public review_url: string | null
    public iat: number
    public exp: number

    constructor(
        contentId: ObjId,
        contentObj: unknown,
        curator: DID,
        rank: number,
        collection: string[],
    ) {
        super()
        const now = nowSeconds()
        this.content_id = contentId.toString()
        this.content_obj = contentObj
        this.curator = curator
        this.editor = []
        this.meta = null
        this.rank = rank
        this.collection = collection
        this.review_url = null
        this.iat = now
        this.exp = now + 3600 * 24 * 30 * 12
    }

    /**
     * Reconstruct an InclusionProof from its JSON form. The decode /
     * re-encode round-trip (fromJSON followed by toJSON) must be
     * byte-stable under canonical JSON, otherwise ObjId verification on a
     * payload produced by the Rust reference impl would drift. That is
     * exactly what the tests under `tests/ndn_types_cases.ts` pin down.
     *
     * Notes on the field mapping:
     *   - `content_id` is passed through ObjId.fromString for validation,
     *     then pinned back to the raw input string so any non-hex-canonical
     *     forms survive the round-trip unchanged (the Rust side doesn't
     *     renormalize on deserialization either).
     *   - `iat` / `exp` must come from the payload, not from the
     *     constructor's `nowSeconds()` defaults, or decoding an older
     *     proof would silently rewrite its validity window.
     */
    static fromJSON(value: Record<string, unknown>): InclusionProof {
        const proof = new InclusionProof(
            ObjId.fromString(String(value.content_id ?? '')),
            value.content_obj ?? null,
            String(value.curator ?? ''),
            Number(value.rank ?? 0),
            Array.isArray(value.collection)
                ? (value.collection as string[]).slice()
                : [],
        )
        proof.content_id = String(value.content_id ?? '')
        proof.editor = Array.isArray(value.editor)
            ? (value.editor as string[]).slice()
            : []
        proof.meta = value.meta ?? null
        proof.review_url = typeof value.review_url === 'string'
            ? value.review_url
            : null
        proof.iat = Number(value.iat ?? 0)
        proof.exp = Number(value.exp ?? 0)
        return proof
    }

    getObjType(): string {
        return OBJ_TYPE_INCLUSION_PROOF
    }

    toJSON(): Record<string, unknown> {
        const out: Record<string, unknown> = {
            content_id: this.content_id,
            content_obj: this.content_obj,
            curator: this.curator,
            editor: this.editor,
            meta: this.meta,
            rank: this.rank,
            iat: this.iat,
            exp: this.exp,
        }
        if (this.collection.length > 0) out.collection = this.collection
        if (this.review_url != null) out.review_url = this.review_url
        return out
    }
}

// ============================================================
// SimpleObjectMap / SimpleMapItem (from simple_object_map.rs)
// ============================================================

export type SimpleMapItem =
    | { kind: 'objId'; objId: ObjId }
    | { kind: 'object'; objType: string; obj: unknown }
    | { kind: 'objectJwt'; objType: string; jwt: string }

export const SimpleMapItem = {
    fromObjId(objId: ObjId): SimpleMapItem {
        return { kind: 'objId', objId }
    },
    fromObject(objType: string, obj: unknown): SimpleMapItem {
        return { kind: 'object', objType, obj }
    },
    fromObjectJwt(objType: string, jwt: string): SimpleMapItem {
        return { kind: 'objectJwt', objType, jwt }
    },

    getObjType(item: SimpleMapItem): string {
        switch (item.kind) {
            case 'objId': return item.objId.objType
            case 'object': return item.objType
            case 'objectJwt': return item.objType
        }
    },

    /** Compute (objId, optional inline obj-string) for this item. */
    getObjId(item: SimpleMapItem): [ObjId, string] {
        switch (item.kind) {
            case 'objId':
                return [item.objId, '']
            case 'object':
                return buildNamedObjectByJson(item.objType, item.obj)
            case 'objectJwt':
                throw new NdnError(
                    'Unsupported',
                    'JWT-encoded SimpleMapItem requires JWT decoding (not implemented in TS port)',
                )
        }
    },

    toJSON(item: SimpleMapItem): unknown {
        switch (item.kind) {
            case 'objId':
                return item.objId.toString()
            case 'object':
                return { obj_type: item.objType, body: item.obj }
            case 'objectJwt':
                return { obj_type: item.objType, jwt: item.jwt }
        }
    },

    fromJSON(value: unknown): SimpleMapItem {
        if (typeof value === 'string') {
            return { kind: 'objId', objId: ObjId.fromString(value) }
        }
        if (value && typeof value === 'object' && !Array.isArray(value)) {
            const v = value as Record<string, unknown>
            const objType = v.obj_type
            if (typeof objType !== 'string') {
                throw new NdnError('InvalidData', 'SimpleMapItem must have obj_type field')
            }
            if (typeof v.jwt === 'string') {
                return { kind: 'objectJwt', objType, jwt: v.jwt }
            }
            if ('body' in v) {
                return { kind: 'object', objType, obj: v.body }
            }
            throw new NdnError('InvalidData', 'SimpleMapItem must have body or jwt field')
        }
        throw new NdnError('InvalidData', 'SimpleMapItem must be string or object')
    },
}

export class SimpleObjectMap {
    public body: Map<string, SimpleMapItem>

    constructor() {
        this.body = new Map()
    }

    static fromJSON(value: unknown): SimpleObjectMap {
        const map = new SimpleObjectMap()
        if (!value || typeof value !== 'object') {
            throw new NdnError('InvalidData', 'SimpleObjectMap must be an object')
        }
        const root = value as Record<string, unknown>
        const body = root.body
        if (body == null) return map
        if (typeof body !== 'object' || Array.isArray(body)) {
            throw new NdnError('InvalidData', 'SimpleObjectMap.body must be an object')
        }
        for (const [k, v] of Object.entries(body as Record<string, unknown>)) {
            map.body.set(k, SimpleMapItem.fromJSON(v))
        }
        return map
    }

    /**
     * Resolve every entry to its ObjId string and merge it into `realObj` as
     * the `body` field, then derive a NamedObject ObjId. Matches
     * SimpleObjectMap::gen_obj_id_with_real_obj() in Rust.
     */
    genObjIdWithRealObj(
        resultObjType: string,
        realObj: Record<string, unknown>,
    ): [ObjId, string] {
        const realMap: Record<string, string> = {}
        for (const [k, v] of this.body) {
            const [subId] = SimpleMapItem.getObjId(v)
            realMap[k] = subId.toString()
        }
        realObj.body = realMap
        return buildNamedObjectByJson(resultObjType, realObj)
    }

    get size(): number {
        return this.body.size
    }

    isEmpty(): boolean {
        return this.body.size === 0
    }

    get(key: string): SimpleMapItem | undefined {
        return this.body.get(key)
    }

    set(key: string, value: SimpleMapItem): void {
        this.body.set(key, value)
    }

    delete(key: string): boolean {
        return this.body.delete(key)
    }

    has(key: string): boolean {
        return this.body.has(key)
    }

    keys(): IterableIterator<string> {
        return this.body.keys()
    }

    values(): IterableIterator<SimpleMapItem> {
        return this.body.values()
    }

    entries(): IterableIterator<[string, SimpleMapItem]> {
        return this.body.entries()
    }

    /** Serialize to wire JSON (matches Rust SimpleObjectMap serde). */
    toJSON(): Record<string, unknown> {
        const body: Record<string, unknown> = {}
        for (const [k, v] of this.body) {
            body[k] = SimpleMapItem.toJSON(v)
        }
        return { body }
    }
}

// ============================================================
// DirObject (from dirobj.rs)
// ============================================================

export class DirObject extends NamedObjectBase {
    public content_obj: BaseContentObject
    public meta: Record<string, unknown>
    public total_size: number
    public file_count: number
    public file_size: number
    public object_map: SimpleObjectMap

    constructor(name?: string) {
        super()
        this.content_obj = name != null
            ? new BaseContentObject({ name })
            : new BaseContentObject()
        this.meta = {}
        this.total_size = 0
        this.file_count = 0
        this.file_size = 0
        this.object_map = new SimpleObjectMap()
    }

    static fromJSON(value: Record<string, unknown>): DirObject {
        const dir = new DirObject()
        const baseKeys = new Set([
            'did', 'name', 'author', 'owner', 'create_time', 'last_update_time',
            'copyright', 'tags', 'categories', 'base_on', 'directory', 'references', 'exp',
        ])
        const baseFields: BaseContentObjectFields = {}
        for (const [k, v] of Object.entries(value)) {
            if (k === 'meta') {
                dir.meta = (v as Record<string, unknown>) ?? {}
            } else if (k === 'total_size') {
                dir.total_size = Number(v ?? 0)
            } else if (k === 'file_count') {
                dir.file_count = Number(v ?? 0)
            } else if (k === 'file_size') {
                dir.file_size = Number(v ?? 0)
            } else if (k === 'body') {
                const body = v as Record<string, unknown>
                if (body) {
                    for (const [name, item] of Object.entries(body)) {
                        dir.object_map.set(name, SimpleMapItem.fromJSON(item))
                    }
                }
            } else if (baseKeys.has(k)) {
                if (k === 'base_on' && typeof v === 'string') {
                    baseFields.base_on = ObjId.fromString(v)
                } else {
                    (baseFields as any)[k] = v
                }
            }
        }
        dir.content_obj = new BaseContentObject(baseFields)
        return dir
    }

    getObjType(): string {
        return OBJ_TYPE_DIR
    }

    /** JSON form (with raw `body`) - useful for storage / debug. */
    toJSON(): Record<string, unknown> {
        const out: Record<string, unknown> = { ...this.content_obj.toJSON() }
        if (Object.keys(this.meta).length > 0) out.meta = this.meta
        out.total_size = this.total_size
        out.file_count = this.file_count
        out.file_size = this.file_size
        out.body = this.object_map.toJSON().body
        return out
    }

    /**
     * DirObject's ObjId is derived from a JSON form whose `body` field is a
     * `name -> objIdString` map (children are reduced to ObjIds first).
     * Matches DirObject::gen_obj_id() in Rust.
     */
    genObjId(): [ObjId, string] {
        const realObj: Record<string, unknown> = { ...this.content_obj.toJSON() }
        realObj.total_size = this.total_size
        realObj.file_count = this.file_count
        realObj.file_size = this.file_size
        // Note: meta is intentionally NOT included here, matching Rust's
        // gen_obj_id() which only writes the BaseContentObject fields plus
        // the three counters before delegating to SimpleObjectMap.
        return this.object_map.genObjIdWithRealObj(OBJ_TYPE_DIR, realObj)
    }

    get size(): number {
        return this.object_map.size
    }

    isEmpty(): boolean {
        return this.object_map.isEmpty()
    }

    get(key: string): SimpleMapItem | undefined {
        return this.object_map.get(key)
    }

    delete(key: string): boolean {
        return this.object_map.delete(key)
    }

    has(key: string): boolean {
        return this.object_map.has(key)
    }

    keys(): IterableIterator<string> {
        return this.object_map.keys()
    }

    values(): IterableIterator<SimpleMapItem> {
        return this.object_map.values()
    }

    entries(): IterableIterator<[string, SimpleMapItem]> {
        return this.object_map.entries()
    }

    addFile(name: string, fileObj: unknown, fileSize: number): void {
        this.file_size += fileSize
        this.file_count += 1
        this.total_size += fileSize
        this.object_map.set(name, SimpleMapItem.fromObject(OBJ_TYPE_FILE, fileObj))
    }

    addDirectory(name: string, dirObjId: ObjId, dirSize: number): void {
        if (dirObjId.objType !== OBJ_TYPE_DIR) {
            throw new NdnError('InvalidParam', 'dir_obj_id is not a directory')
        }
        this.total_size += dirSize
        this.object_map.set(name, SimpleMapItem.fromObjId(dirObjId))
    }

    listEntries(): string[] {
        return Array.from(this.object_map.keys())
    }

    isFile(name: string): boolean {
        const item = this.object_map.get(name)
        if (!item) return false
        return item.kind === 'object' && item.objType === OBJ_TYPE_FILE
    }

    isDirectory(name: string): boolean {
        const item = this.object_map.get(name)
        if (!item) return false
        switch (item.kind) {
            case 'objId': return item.objId.objType === OBJ_TYPE_DIR
            case 'objectJwt': return item.objType === OBJ_TYPE_DIR
            default: return false
        }
    }
}

// ============================================================
// SimpleChunkList (from chunk/simple_chunk_list.rs)
// ============================================================

export class SimpleChunkList {
    public total_size: number
    public body: ChunkId[]

    constructor() {
        this.total_size = 0
        this.body = []
    }

    static fromChunkList(chunks: ChunkId[]): SimpleChunkList {
        const list = new SimpleChunkList()
        for (const c of chunks) {
            const len = c.getLength()
            if (len == null) {
                throw new NdnError('InvalidParam', 'get chunk length from chunkid failed')
            }
            list.total_size += len
        }
        list.body = chunks.slice()
        return list
    }

    static fromJson(objStr: string): SimpleChunkList {
        let parsed: unknown
        try {
            parsed = JSON.parse(objStr)
        } catch (e) {
            throw new NdnError(
                'InvalidParam',
                `parse chunk list from json failed: ${(e as Error).message}`,
            )
        }
        return SimpleChunkList.fromJsonValue(parsed)
    }

    static fromJsonValue(value: unknown): SimpleChunkList {
        if (!Array.isArray(value)) {
            throw new NdnError('InvalidParam', 'chunk list must be a JSON array')
        }
        const chunks = value.map(item => {
            if (typeof item !== 'string') {
                throw new NdnError('InvalidParam', 'chunk list item must be a string')
            }
            return ChunkId.fromString(item)
        })
        return SimpleChunkList.fromChunkList(chunks)
    }

    appendChunk(chunkId: ChunkId): void {
        const len = chunkId.getLength()
        if (len == null) {
            throw new NdnError('InvalidParam', 'get chunk length from chunkid failed')
        }
        this.body.push(chunkId)
        this.total_size += len
    }

    /**
     * Mirrors SimpleChunkList::gen_obj_id(): hash the JSON list of ChunkId
     * strings, then prefix the resulting hash bytes with varint(total_size)
     * to form the final ObjId.
     */
    genObjId(): [ObjId, string] {
        const bodyJson = this.body.map(c => c.toString())
        const [innerObjId, objStr] = buildNamedObjectByJson(
            OBJ_TYPE_CHUNK_LIST_SIMPLE,
            bodyJson,
        )
        const mixed = ChunkId.mixLengthAndHashResult(this.total_size, innerObjId.objHash)
        const resultId = ObjId.fromRaw(OBJ_TYPE_CHUNK_LIST_SIMPLE, mixed)
        return [resultId, objStr]
    }
}

// ============================================================
// RelationObject (from relation_obj.rs)
// ============================================================

export type ObjectLinkData =
    | { kind: 'sameAs'; target: ObjId }
    | { kind: 'partOf'; target: ObjId; range: { start: number; end: number } }

export class RelationObject extends NamedObjectBase {
    public source: ObjId
    public relation: string
    public target: ObjId
    public body: Record<string, unknown>
    public iat: number | null
    public exp: number | null

    constructor(
        source: ObjId,
        relation: string,
        target: ObjId,
        body: Record<string, unknown> = {},
    ) {
        super()
        this.source = source
        this.relation = relation
        this.target = target
        this.body = body
        this.iat = null
        this.exp = null
    }

    /**
     * Reconstruct a RelationObject from its JSON form. `source`, `relation`,
     * `target`, `iat` and `exp` are reserved top-level fields; every other
     * key lands back in `body` (matching what `toJSON` spreads out), so the
     * decode → re-encode round-trip is byte-stable under canonical JSON
     * for any shape the TS class is capable of emitting.
     */
    static fromJSON(value: Record<string, unknown>): RelationObject {
        const reserved = new Set(['source', 'relation', 'target', 'iat', 'exp'])
        const body: Record<string, unknown> = {}
        for (const [k, v] of Object.entries(value)) {
            if (!reserved.has(k)) body[k] = v
        }
        const rel = new RelationObject(
            ObjId.fromString(String(value.source ?? '')),
            String(value.relation ?? ''),
            ObjId.fromString(String(value.target ?? '')),
            body,
        )
        rel.iat = typeof value.iat === 'number' ? value.iat : null
        rel.exp = typeof value.exp === 'number' ? value.exp : null
        return rel
    }

    static createByLinkData(source: ObjId, link: ObjectLinkData): RelationObject {
        switch (link.kind) {
            case 'sameAs':
                return new RelationObject(source, RELATION_TYPE_SAME, link.target)
            case 'partOf':
                return new RelationObject(
                    source,
                    RELATION_TYPE_PART_OF,
                    link.target,
                    { range: { start: link.range.start, end: link.range.end } },
                )
        }
    }

    getLinkData(): ObjectLinkData {
        switch (this.relation) {
            case RELATION_TYPE_SAME:
                return { kind: 'sameAs', target: this.target }
            case RELATION_TYPE_PART_OF: {
                const range = this.body.range as { start?: unknown; end?: unknown } | undefined
                if (!range || typeof range.start !== 'number' || typeof range.end !== 'number') {
                    throw new NdnError(
                        'InvalidLink',
                        `invalid range: ${JSON.stringify(this.body.range)}`,
                    )
                }
                return {
                    kind: 'partOf',
                    target: this.target,
                    range: { start: range.start, end: range.end },
                }
            }
            default:
                throw new NdnError('InvalidLink', `invalid relation: ${this.relation}`)
        }
    }

    getObjType(): string {
        return OBJ_TYPE_RELATION
    }

    toJSON(): Record<string, unknown> {
        const out: Record<string, unknown> = {
            source: this.source.toString(),
            relation: this.relation,
            target: this.target.toString(),
        }
        for (const [k, v] of Object.entries(this.body)) {
            out[k] = v
        }
        if (this.iat != null) out.iat = this.iat
        if (this.exp != null) out.exp = this.exp
        return out
    }
}

// ============================================================
// KnownStandardObject (from lib.rs)
// ============================================================

export type KnownStandardObject =
    | { kind: 'dir'; obj: DirObject; objStr: string }
    | { kind: 'file'; obj: FileObject; objStr: string }
    | { kind: 'chunkList'; obj: SimpleChunkList; objStr: string }

export const KnownStandardObject = {
    fromObjData(objId: ObjId, objData: string): KnownStandardObject {
        switch (objId.objType) {
            case OBJ_TYPE_DIR: {
                let parsed: unknown
                try {
                    parsed = JSON.parse(objData)
                } catch (e) {
                    throw new NdnError(
                        'InvalidParam',
                        `parse dir object from json failed: ${(e as Error).message}`,
                    )
                }
                return {
                    kind: 'dir',
                    obj: DirObject.fromJSON(parsed as Record<string, unknown>),
                    objStr: objData,
                }
            }
            case OBJ_TYPE_FILE: {
                let parsed: unknown
                try {
                    parsed = JSON.parse(objData)
                } catch (e) {
                    throw new NdnError(
                        'InvalidParam',
                        `parse file object from json failed: ${(e as Error).message}`,
                    )
                }
                return {
                    kind: 'file',
                    obj: FileObject.fromJSON(parsed as Record<string, unknown>),
                    objStr: objData,
                }
            }
            case OBJ_TYPE_CHUNK_LIST_SIMPLE: {
                return {
                    kind: 'chunkList',
                    obj: SimpleChunkList.fromJson(objData),
                    objStr: objData,
                }
            }
            default:
                throw new NdnError('InvalidParam', `Unknown object type: ${objId.objType}`)
        }
    },

    /** Return ObjIds (and optional inline obj-string) for the children. */
    getChildObjs(known: KnownStandardObject): Array<{ objId: ObjId; objStr: string | null }> {
        switch (known.kind) {
            case 'dir': {
                const out: Array<{ objId: ObjId; objStr: string | null }> = []
                for (const [, item] of known.obj.entries()) {
                    const [objId, objStr] = SimpleMapItem.getObjId(item)
                    out.push({ objId, objStr: objStr.length > 0 ? objStr : null })
                }
                return out
            }
            case 'file': {
                if (known.obj.content.length === 0) return []
                return [{ objId: ObjId.fromString(known.obj.content), objStr: null }]
            }
            case 'chunkList':
                return known.obj.body.map(c => ({ objId: c.toObjId(), objStr: null }))
        }
    },
}

// ============================================================
// UTF-8 helpers (browser+node)
// ============================================================

const _textEncoder: { encode(s: string): Uint8Array } | null =
    typeof TextEncoder !== 'undefined' ? new TextEncoder() : null
const _textDecoder: { decode(b: Uint8Array): string } | null =
    typeof TextDecoder !== 'undefined' ? new TextDecoder('utf-8') : null

function utf8Encode(s: string): Uint8Array {
    if (_textEncoder) return _textEncoder.encode(s)
    // Fallback (very small targets / older runtimes).
    const out: number[] = []
    for (let i = 0; i < s.length; i++) {
        let c = s.charCodeAt(i)
        if (c < 0x80) {
            out.push(c)
        } else if (c < 0x800) {
            out.push(0xc0 | (c >> 6), 0x80 | (c & 0x3f))
        } else if (c >= 0xd800 && c <= 0xdbff && i + 1 < s.length) {
            const c2 = s.charCodeAt(++i)
            const cp = 0x10000 + (((c & 0x3ff) << 10) | (c2 & 0x3ff))
            out.push(
                0xf0 | (cp >> 18),
                0x80 | ((cp >> 12) & 0x3f),
                0x80 | ((cp >> 6) & 0x3f),
                0x80 | (cp & 0x3f),
            )
        } else {
            out.push(0xe0 | (c >> 12), 0x80 | ((c >> 6) & 0x3f), 0x80 | (c & 0x3f))
        }
    }
    return new Uint8Array(out)
}

function utf8Decode(bytes: Uint8Array): string {
    if (_textDecoder) return _textDecoder.decode(bytes)
    let s = ''
    let i = 0
    while (i < bytes.length) {
        const b = bytes[i++]
        if (b < 0x80) {
            s += String.fromCharCode(b)
        } else if (b < 0xe0) {
            s += String.fromCharCode(((b & 0x1f) << 6) | (bytes[i++] & 0x3f))
        } else if (b < 0xf0) {
            s += String.fromCharCode(
                ((b & 0x0f) << 12) | ((bytes[i++] & 0x3f) << 6) | (bytes[i++] & 0x3f),
            )
        } else {
            const cp =
                ((b & 0x07) << 18) |
                ((bytes[i++] & 0x3f) << 12) |
                ((bytes[i++] & 0x3f) << 6) |
                (bytes[i++] & 0x3f)
            const u = cp - 0x10000
            s += String.fromCharCode(0xd800 + (u >> 10), 0xdc00 + (u & 0x3ff))
        }
    }
    return s
}
